version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    day: saturday
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: "@types/node"
    versions:
    - ">= 14.a, < 15"
  - dependency-name: "@types/node"
    versions:
    - 15.0.1
    - 15.0.2
  - dependency-name: "@pulumi/gcp"
    versions:
    - 5.2.0
  - dependency-name: "@pulumi/pulumi"
    versions:
    - 3.1.0
