#!/bin/bash
# shellcheck disable=SC2128

set -ex

script_dir="$(dirname "$BASH_SOURCE")"
sshuttle_command="sshuttle -v --dns --remote \"$("$script_dir/pulumi-stack-output" sshDestination)\" --ssh-cmd \"$script_dir/ssh\" 0/0 $*"
"$script_dir/watchdog" "$sshuttle_command"
